- hosts: dockerhosts
  tasks:
    - name: "Installing Docker Prerequisite Packages"
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - yum_utils
        - device-mapper-persistent-data
        - lvm2
        
    - name: Add Docker repo
      yum_repository:
        baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
        name: docker
        gpgcheck: no
        description: YUM DOCKER REPO
      register: x
      
    - name: Install Docker
      package:
        name: "docker-ce-18.09.1-3.el7.x86_64"
        state: present
      register: a
      
    - debug:
        var: a
        
    - name: Start Docker Service
      service:
        name: docker 
        state: started
        enabled: yes
        
